package com.timepath.swing;

import java.util.logging.Logger;
import javax.swing.JToolBar;

/**
 *
 * @author timepath
 */
@SuppressWarnings("serial")
public class StatusBar extends JToolBar {

    /**
     * Creates new form BlendedToolBar
     */
    public StatusBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFloatable(false);
        setMaximumSize(new java.awt.Dimension(32767, 20));
        setMinimumSize(new java.awt.Dimension(2, 20));
        setPreferredSize(new java.awt.Dimension(2, 20));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private static final Logger LOG = Logger.getLogger(StatusBar.class.getName());
}
