package com.timepath.vgui

import com.timepath.vgui.controls.CExLabel
import java.util.logging.Level
import java.util.logging.Logger

/**
 * @author TimePath
 */
public object Controls {

    private val LOG = Logger.getLogger(Controls.javaClass.getName())

    public fun get(type: String): Class<out Control> = when (type) {
        "CExLabel" -> javaClass<CExLabel>()
        "CIconPanel" -> javaClass<Control>()
        "CTeamMenu" -> javaClass<Control>()
        "CTFClassInfoPanel" -> javaClass<Control>()
        "CTFArrowPanel" -> javaClass<Control>()
        "CTFImagePanel" -> javaClass<Control>()
        "CEmbeddedItemModelPanel" -> javaClass<Control>()
        "CTFHudTimeStatus" -> javaClass<Control>()
        "CWaveStatusPanel" -> javaClass<Control>()
        "CControlPointCountdown" -> javaClass<Control>()
        "CWaveCompleteSummaryPanel" -> javaClass<Control>()
        "CTFTextWindow" -> javaClass<Control>()
        "CTFRichText" -> javaClass<Control>()
        "CTankStatusPanel" -> javaClass<Control>()
        "CExImageButton" -> javaClass<Control>()
        "CEngyDestroyMenuItem" -> javaClass<Control>()
        "CCurrencyStatusPanel" -> javaClass<Control>()
        "CTFClassImage" -> javaClass<Control>()
        "CInWorldCurrencyStatus" -> javaClass<Control>()
        "CTFClientScoreBoardDialog" -> javaClass<Control>()
        "CTFHudEscort" -> javaClass<Control>()
        "CWarningSwoop" -> javaClass<Control>()
        "CItemModelPanel" -> javaClass<Control>()
        "CStoreItemControlsPanel" -> javaClass<Control>()
        "CExButton" -> javaClass<Control>()
        "CStorePreviewItemPanel" -> javaClass<Control>()
        "CStorePricePanel" -> javaClass<Control>()
        "CRichTextWithScrollbarBorders" -> javaClass<Control>()
        "CTFPlayerModelPanel" -> javaClass<Control>()
        "CArmoryPanel" -> javaClass<Control>()
        "CNotificationsPresentPanel" -> javaClass<Control>()
        "CEconItemDetailsRichText" -> javaClass<Control>()
        "CTFMapStampsInfoDialog" -> javaClass<Control>()
        "CStorePreviewItemIcon" -> javaClass<Control>()
        "CMouseMessageForwardingPanel" -> javaClass<Control>()
        "CGenericNotificationToast" -> javaClass<Control>()
        "CStorePreviewClassIcon" -> javaClass<Control>()
        "CNavigationPanel" -> javaClass<Control>()
        "CAvatarImagePanel" -> javaClass<Control>()
        "CNotificationQueuePanel" -> javaClass<Control>()
        "CPreviewRotButton" -> javaClass<Control>()
        "CNotificationToastControl" -> javaClass<Control>()
        "CItemMaterialCustomizationIconPanel" -> javaClass<Control>()
        "CImagePanel" -> javaClass<Control>()
        "CExplanationPopup" -> javaClass<Control>()
        "CRGBAImagePanel" -> javaClass<Control>()
        "CBackpackPanel" -> javaClass<Control>()
        "CModePanel" -> javaClass<Control>()
        "CTrainingDialog" -> javaClass<Control>()
        "CAchievementsDialog" -> javaClass<Control>()
        "CClassMenu" -> javaClass<Control>()
        "CBitmapPanel" -> javaClass<Control>()
        "CModeSelectionPanel" -> javaClass<Control>()
        "CCustomTextureImagePanel" -> javaClass<Control>()
        "CTFClassTipsItemPanel" -> javaClass<Control>()
        "CBasicTraining_ClassSelectionPanel" -> javaClass<Control>()
        "CBasicTraining_ClassDetailsPanel" -> javaClass<Control>()
        "COfflinePractice_ModeSelectionPanel" -> javaClass<Control>()
        "COfflinePractice_MapSelectionPanel" -> javaClass<Control>()
        "CLoadoutPresetPanel" -> javaClass<Control>()
        "CClassLoadoutPanel" -> javaClass<Control>()
        "CBuildingHealthBar" -> javaClass<Control>()
        "CBuildingStatusAlertTray" -> javaClass<Control>()
        "CTFFreezePanelHealth" -> javaClass<Control>()
        "CTFTeamButton" -> javaClass<Control>()
        "CModelPanel" -> javaClass<Control>()
        "CTFFooter" -> javaClass<Control>()
        "CMvMBombCarrierProgress" -> javaClass<Control>()
        "CTFProgressBar" -> javaClass<Control>()
        "CVictorySplash" -> javaClass<Control>()
        "CMvMVictoryPanelContainer" -> javaClass<Control>()
        "CMvMWaveLossPanel" -> javaClass<Control>()
        "CExRichText" -> javaClass<Control>()
        "CTFIntroMenu" -> javaClass<Control>()
        "CTFVideoPanel" -> javaClass<Control>()
        "CTFLayeredMapItemPanel" -> javaClass<Control>()
        "CTFClassTipsPanel" -> javaClass<Control>()
        "CBaseModelPanel" -> javaClass<Control>()
        "CCreditDisplayPanel" -> javaClass<Control>()
        "CCreditSpendPanel" -> javaClass<Control>()
        "CVictoryPanel" -> javaClass<Control>()
        "CMvMVictoryMannUpPanel" -> javaClass<Control>()
        "CMvMVictoryMannUpEntry" -> javaClass<Control>()
        "CTFHudEscortProgressBar" -> javaClass<Control>()
        "CPublishFileDialog" -> javaClass<Control>()
        "CPublishedFileBrowserDialog" -> javaClass<Control>()
        "CQuickPlayBusyDialog" -> javaClass<Control>()
        "CQuickplayDialog" -> javaClass<Control>()
        "CMainMenuNotificationsControl" -> javaClass<Control>()
        "CSteamWorkshopDialog" -> javaClass<Control>()
        "CSteamWorkshopItemPanel" -> javaClass<Control>()
        "CTankProgressBar" -> javaClass<Control>()
        "CPanelListPanel" -> javaClass<Control>()
        "CTrainingItemPanel" -> javaClass<Control>()
        "CTFTrainingComplete" -> javaClass<Control>()
        "CImageButton" -> javaClass<Control>()
        "CCommentaryExplanationDialog" -> javaClass<Control>()
        "CCommentaryItemPanel" -> javaClass<Control>()
        "CTGAImagePanel" -> javaClass<Control>()
        "COfflinePracticeServerPanel" -> javaClass<Control>()
        "CLoadGameDialog" -> javaClass<Control>()
        "CNewGameDialog" -> javaClass<Control>()
        "COptionsSubMultiplayer" -> javaClass<Control>()
        "CPlayerListDialog" -> javaClass<Control>()
        "CVoteSetupDialog" -> javaClass<Control>()
        "CCvarSlider" -> javaClass<Control>()
        "CControllerMap" -> javaClass<Control>()
        "CScenarioInfoPanel" -> javaClass<Control>()
        "CTFButton" -> javaClass<Control>()
        "CTFImageButton" -> javaClass<Control>()
        "CTFFlagStatus" -> javaClass<Control>()
        "CTFHudMannVsMachineScoreboard" -> javaClass<Control>()
        "CReplayReminderPanel" -> javaClass<Control>()
        "CircularProgressBar" -> javaClass<Control>()
        "PanelListPanel" -> javaClass<Control>()
        "ImageButton" -> javaClass<Control>()
        "RichText" -> javaClass<Control>()
        "SectionedListPanel" -> javaClass<Control>()
        "ListPanel" -> javaClass<Control>()
        "RoundInfoOverlay" -> javaClass<Control>()
        "ProgressBar" -> javaClass<Control>()
        "Slider" -> javaClass<Control>()
        "Divider" -> javaClass<Control>()
        "AnalogBar" -> javaClass<Control>()
        "FooterPanel" -> javaClass<Control>()
        "AnimatingImagePanel" -> javaClass<Control>()
        "RotatingProgressBar" -> javaClass<Control>()
        "MaterialButton" -> javaClass<Control>()
        "CustomTextureStencilGradientMapWidget" -> javaClass<Control>()
        "RadioButton" -> javaClass<Control>()
        "ScrollableEditablePanel" -> javaClass<Control>()
        "CheckButton" -> javaClass<Control>()
        "ComboBox" -> javaClass<Control>()
        "ScrollBar" -> javaClass<Control>()
        "Button" -> javaClass<Control>()
        "Panel" -> javaClass<Control>()
        "ImagePanel" -> javaClass<Control>()
        "ContinuousProgressBar" -> javaClass<Control>()
        "Menu" -> javaClass<Control>()
        "EditablePanel" -> javaClass<Control>()
        "Frame" -> javaClass<Control>()
        "ScalableImagePanel" -> javaClass<Control>()
        "Label" -> javaClass<Control>()
        "HTML" -> javaClass<Control>()
        "TextEntry" -> javaClass<Control>()
        else -> {
            LOG.log(Level.WARNING, "Unknown control: {0}", type)
            javaClass<Control>()
        }
    }
}
